### ISSUE TITLE
проблема с немонтированными томами

### ISSUE THREAD

**Issue by ccaid** [smithx/far#7]
с давних пор Far умеет работать с немонтированными томами, а с некоторых пор такие тома доступны из меню выбора диска (если нажать CtrlH).
путь таких томов выглядит как-то так: `\\?\Volume{7e734d22-3b75-4eb5-9446-bab0d550f50c}`.

внезапно выяснилось, что GitBranch не рассчитывает на подобные пути. после входа в любую папку на таком томе Far с загруженным GitBranch перестаёт реагировать на клавиатуру (и мышь), закрывать только по крестику. возможно, через полчаса он и отмораживается, такие опыты я не проводил.

**Comment by smithx** [comment]
если за разумное время [не починят](https://github.com/libgit2/libgit2/issues/6524), будут приседать у себя

**Comment by smithx** [comment]
в 3.0.23 должно быть исправлено
